language: node_js
node_js:
  - node
  - "5"
  - "4"
  - "0"
addons:
  code_climate:
    repo_token: c847dfc69d1d803941388efc43666a297f640a76d67b87084bdb08a6eafb5cc6
script:
  - npm run build
  - npm run coverage
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: hello@stephenzuniga.com
  api_key:
    secure: Ok0rW/4xI4D2oe7rAlfo3nEqGulDK9eqj9ytKdKDEy0KHLoU13b91rS7KXBvQCsM+lh4JQaErE6WaFRFROzV4UJiwz3BIPz3Aaarz3zbFs50nY05Vrsn9lNFay7yW1ti/7lccem1gxzpA3DPuFGGJyQRc0GPmKl2VY/oASQ36gxxN7b0Mp2rTEYOvveo6cg2rorKxC6Tr9dEa5WhcrThh5raX86gWRxIF7XFeCN89Lj8V1hpxi8Msf+peo4X+PJmMbncnknNiGXsi4QKBBxWH1e4KPp4pVrgTxIpb/14m3/FH36pNffgoE3Bul5yt3BgSfacINRLiFTiKyOD1MaLX91y4rcaIQu54TGkdcdH9euIBkS3BXTxfYAEORRuQh52CsZsHhjo38tMQqZBEKDjyE+ypxIUMIc/wVenwN6u04o53O6fxqwlSwob8w2N1gHxdp/PGYxorVqDeqsuuiJmDJ3dNHj7o36CQTCFTjNcPpAFCSldrLoTVFNgGfNgAWCxmxEEI95dbEnnlSozhX7LaR/PbIS0s24Q7Jvu6fOi1dlPb7dzf0zXsEOT6Ng9i5jOzXPE23GbHmceYR55QMxn2ZP2U/ZrlqfICMYh/y/3xkXhS2B3BD2+6i6n+xRDQhXQxKQ8gX1SQC60W/TXncgxoF+toT9xxgsYuagmgmHuEGY=
  on:
    tags: true
    repo: stezu/gulp-grandma
